// Generated by CoffeeScript 1.10.0
(function() {
  var jsonref, o;

  jsonref = require('json-ref-lite/index.coffee')();

  o = {};

  o.parse = function(uimodel) {
    return jsonref.resolve(uimodel);
  };

  module.exports = o;

}).call(this);
