// Generated by CoffeeScript 1.10.0
(function() {
  var fs, jsonref, mustache, o;

  jsonref = require('json-ref-lite/index.coffee')();

  mustache = require('mustache');

  fs = require('fs');

  o = {};

  o.parse = function(uimodel) {};

  o.register_mustache_filters = function(data) {
    return data.foo = function() {
      return function(text, render) {
        return "" + render(text) + "";
      };
    };
  };

  o.render = function(tplfile, data, jscode) {
    var tpl;
    this.register_mustache_filters(data);
    tpl = fs.readFileSync(__dirname + "/../../src/mustache/" + tplfile).toString();
    return jscode.push(mustache.render(tpl, data));
  };

  module.exports = o;

}).call(this);
